### ISSUE TITLE
Mac更新catalina，git命令报错

### ISSUE THREAD

**Issue by jason-zzq** [wit-course/aio#3]
**Describe the bug**
mac由mojave更新到catalina后，git命令报错

**To Reproduce**
1. 在app store中点击Get Mac catalina。
2. 进入更新，install catalina。
3. 更新完成后重启。
4. 打开终端，进入cc repo，输入git branch -a。

**Expected behavior**
查看当前repo所有分支

**Desktop (please complete the following information):**
 - OS:  macOS Catalina
 - Terminal:  iTerm2
 - Shell:  zsh

**Additional context**
Error log:
```shell
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

**Comment by conke** [comment]
xcrun这是Xcode相关的命令行工具，git是无辜的。
解决方法：请尝试重装Xcode (新版xcode已经发布)。

**Comment by conke** [comment]
PS, 最后的error log应该放在开头的description里
