### ISSUE TITLE
Mac更新catalina，无法连接App store

### ISSUE THREAD

**Issue by jason-zzq** [wit-course/aio#4]
**Describe the bug**
mac由mojave更新到catalina后，登陆账户后提示an unexpected error occurred while signing in.无法登陆

**To Reproduce**
1. 在app store中点击Get Mac catalina。
2. 进入更新，install catalina。
3. 更新完成后重启。
4. 打开App store，点击get Xcode，弹出登陆页面后输入了密码

**Expected behavior**
可以登陆Apple ID并下载Xcode

**Desktop (please complete the following information):**
 - OS: [macOS Catalina]
 - App store

**Comment by conke** [comment]
尝试：打开clover，在smbios页面重新生成ID
